[project]
name = "edu-cli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "icecream>=2.1.3",
    "playwright>=1.49.0",
    "python-dotenv>=1.0.1",
    "selectolax>=0.3.26",
    "typer>=0.13.1",
    "xlwings>=0.33.4",
]
